const mongoose = require("mongoose");
const db = require("../models");

// This file empties the Books collection and inserts the books below

mongoose.connect(
  process.env.MONGODB_URI ||
  "mongodb://localhost/WinesDB"
);

const wineSeed = [
  {
    name: "Thomas Fogarty Santa Cruz Mountains Chardonnay 2014",
    color: "white",
    red1_white0: 0,
    wine_region: "California",
    grape_variety: "chardonnay",
    price: 32.29,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "medium+",
    acidNum: 4,
    tannin: "na",
    tannNum: 1,
    alcohol: "medium",
    alcoNum: 3,
    body: "medium+",
    bodyNum: 4,
    unoaked1_oaked5: 5,
    fruity1_savory5: 1,
    alcohol_by_volume: 14,
    organic: true,
    biodynamic: true,
    flavor_characteristics: "A hint of white blossoms, creamy aroma open to tart lemon and lime flavors layered with ripe apple and peach. Crisp fruit balances silky texture. ",
    food_pairing: "",
    image: "",
    url: "https://shop.fogartywinery.com/2014-santa-cruz-mountains-chardonnay-p269.aspx",
    description: "Santa Cruz Mountains is one of the lesser known sites in California. The winery’s elevation at 2000ft along with ideal climate and sun exposure offer optimal growing conditions for the Chardonnay. Well-structured wine balancing refreshing acidity with fresh fruit. Oak aging gives it a beautiful silky texture.",

  },
  {
    name: "Dr. Burklin-Wolf Pfalz Wachenheimer Dry Riesling 2017",
    color: "white",
    red1_white0: 0,
    wine_region: "Germany",
    grape_variety: "riesling",
    price: 18.99,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "high",
    acidNum: 5,
    tannin: "na",
    tannNum: 1,
    alcohol: "medium",
    alcoNum: 3,
    body: "medium",
    bodyNum: 3,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 12,
    organic: false,
    biodynamic: true,
    flavor_characteristics: "Lemon and floral. A touch of minerality.",
    food_pairing: "",
    image: "",
    url: "https://downtoearthwines.net/product/2015-burklin-wolf-wachenheimer-rechbachel-riesling-premier-cru/?utm_medium=pref-cpc&utm_source=vivino-ppc",
    description: "The Pfalz region of Germany produces elegant Rieslings with body and depth. This wine is a fine example that shows fruit and refreshing acidity. Fruit gives way to mineral chalkiness adding complexity. Lingering finish makes you relish this gem of a wine.",

  },
  {
    name: "Hubert Rousseau Domaine des Trois Toits Muscadet Sevre-et-Maine Sur-Lie 2015",
    color: "white",
    red1_white0: 0,
    wine_region: "France",
    grape_variety: "melon de bourgogne",
    price: 16.00,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "high",
    acidNum: 5,
    tannin: "na",
    tannNum: 1,
    alcohol: "high",
    alcoNum: 5,
    body: "full",
    bodyNum: 5,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 16,
    organic: false,
    biodynamic: false,
    flavor_characteristics: "Preserved lemon, green apple, briny, and mineral. Lager-like in its mouth feel. ",
    food_pairing: "",
    image: "",
    url: "",
    description: "Hubert Rousseau specializes in the production of Muscadet. His unique winemaking is characterized by the fermentation and aging method in an underground concrete vessel. The resulting wine has mouth-watering acidity contrasted by the round mouth feel coming from the lie, or the dead yeast cells. The wine’s flavor and texture develop during fermentation sur-lie, through its contact with the dead yeast cells. The wine’s flavors are redolent of preserved lemon and green apple, finishing with saltiness and granite. Mosaics of flavors make for a treat especially at this price point.",

  },
  {
    name: "Domaine Paul Buisse Touraine Sauvignon 2017",
    color: "white",
    red1_white0: 0,
    wine_region: "France",
    grape_variety: "sauvignon blanc",
    price: 13.99,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "medium",
    acidNum: 3,
    tannin: "na",
    tannNum: 1,
    alcohol: "medium",
    alcoNum: 3,
    body: "medium",
    bodyNum: 3,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 13,
    organic: false,
    biodynamic: false,
    flavor_characteristics: "Grapefruit and lime flavors abound, along with delicate herbal notes of thyme and grass.",
    food_pairing: "",
    image: "",
    url: "",
    description: "Great value from the Touraine region of the Loire Valley. The wines age in Cave de la Boule Blance, caves that were carved into ancient limestone rocks. The wine is marked by grapefruit and lime flavors along with delicate notes of thyme and grass. Flavors wound tightly around its restrained yet expressive acidity. It is elegant at its best.",

  },
  {
    name: "Domaine Huet Vouvray Le Mont Sec 2017",
    color: "white",
    red1_white0: 0,
    wine_region: "France",
    grape_variety: "chenin blanc",
    price: 37.98,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "high",
    acidNum: 5,
    tannin: "na",
    tannNum: 1,
    alcohol: "medium",
    alcoNum: 3,
    body: "medium+",
    bodyNum: 4,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 12,
    organic: false,
    biodynamic: false,
    flavor_characteristics: "Orchard fruits apple and pear, as well as floral notes of honeysuckle and orange blossoms. Honey and and wet straw with lean minerality. ",
    food_pairing: "",
    image: "",
    url: "",
    description: "Le Mont Sec is considered one of Domaine Huet’s greatest vineyards. Its wines exude aromas of yellow apple and ripe pear laced with honeysuckle and orange blossoms. On the palate the flavors of these orchard fruits are layered with a taste of honey and stony minerality. These rich flavors mask and balance the mouth-puckering acidity. It can be drunk now, but the high acidity encourages cellaring; wine will evolve into one of great complexity. A sublime wine.",

  },
  { 
    name: "Trimbach Gewurztraminer 2015",
    color: "white",
    red1_white0: 0,
    wine_region: "France",
    grape_variety: "gewurztraminer",
    price: 18.99,
    sparkling1_still5: 0,
    sweetness: "off dry",
    sweetNum: 2,
    acidity: "low",
    acidNum: 1,
    tannin: "na",
    tannNum: 1,
    alcohol: "medium",
    alcoNum: 3,
    body: "medium+",
    bodyNum: 4,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 14,
    organic: false,
    biodynamic: false,
    flavor_characteristics: "Tropical notes of lychee, passion fruit and pineapple.",
    food_pairing: "",
    image: "",
    url: "",
    description: "A 13-generation family owned winemakers, Trimbach produces one of the most quintessential expressions of Gewurztraminer. Their vineyards in the Alsace’s Ribeauville are renowned for their microclimate and the spectacular geological formations that produced mosaic layers of various soil types. The wine is aged for 2 years in stainless steel vessel to preserve the freshness of the fruit. Flavors of tropical fruits lychee, passion fruit, and pineapple make for a very pretty wine with a lot of character.",

  },
  { 
    name: "Duckhorn Napa Valley Merlot 2015",
    color: "red",
    red1_white0: 1,
    wine_region: "California",
    grape_variety: "merlot",
    price: 44.99,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "medium+",
    acidNum: 4,
    tannin: "medium+",
    tannNum: 4,
    alcohol: "medium+",
    alcoNum: 4,
    body: "full",
    bodyNum: 5,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 15,
    organic: true,
    biodynamic: true,
    flavor_characteristics: "",
    food_pairing: "",
    image: "",
    url: "",
    description: "",

  },
  { 
    name: "Camp Merlot Sonoma County",
    color: "red",
    red1_white0: 1,
    wine_region: "California",
    grape_variety: "merlot",
    price: 16.99,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "medium",
    acidNum: 3,
    tannin: "medium+",
    tannNum: 4,
    alcohol: "medium",
    alcoNum: 03,
    body: "medium+",
    bodyNum: 04,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 13,
    organic: true,
    biodynamic: true,
    flavor_characteristics: "",
    food_pairing: "",
    image: "",
    url: "",
    description: "",

  },
  { 
    name: "Grgich Hills Estate Cabernet Sauvignon Napa Valley",
    color: "red",
    red1_white0: 1,
    wine_region: "California",
    grape_variety: "cabernet sauvignon",
    price: 39.99,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "medium+",
    acidNum: 4,
    tannin: "high",
    tannNum: 5,
    alcohol: "medium+",
    alcoNum: 4,
    body: "full",
    bodyNum: 05,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 15,
    organic: true,
    biodynamic: true,
    flavor_characteristics: "",
    food_pairing: "",
    image: "",
    url: "",
    description: "",

  },
  { 
    name: "Noble Hill Cabernet Sauvignon",
    color: "re",
    red1_white0: 1,
    wine_region: "California",
    grape_variety: "cabernet sauvignon",
    price: 23.99,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "medium+",
    acidNum: 4,
    tannin: "medium+",
    tannNum: 4,
    alcohol: "medium",
    alcoNum: 3,
    body: "medium+",
    bodyNum: 4,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 14,
    organic: true,
    biodynamic: true,
    flavor_characteristics: "",
    food_pairing: "",
    image: "",
    url: "",
    description: "",

  },
  { 
    name: "Cabot Vineyards Humboldt Syrah 2011",
    color: "red",
    red1_white0: 1,
    wine_region: "California",
    grape_variety: "syrah",
    price: 27.00,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "medium",
    acidNum: 03,
    tannin: "medium+",
    tannNum: 4,
    alcohol: "medium",
    alcoNum: 3,
    body: "medium+",
    bodyNum: 4,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 14,
    organic: true,
    biodynamic: true,
    flavor_characteristics: "",
    food_pairing: "",
    image: "",
    url: "",
    description: "",

  },
  { 
    name: "Barossa Valley Shiraz Hewitson Ned & Henry’s",
    color: "red",
    red1_white0: 1,
    wine_region: "Australia",
    grape_variety: "syrah",
    price: 17.00,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "medium+",
    acidNum: 4,
    tannin: "medium+",
    tannNum: 4,
    alcohol: "medium+",
    alcoNum: 4,
    body: "full",
    bodyNum: 5,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 15,
    organic: true,
    biodynamic: true,
    flavor_characteristics: "",
    food_pairing: "",
    image: "",
    url: "",
    description: "",

  },
  { 
    name: "Prunatelli Chianti Rufina Riserva",
    color: "red",
    red1_white0: 1,
    wine_region: "Italy",
    grape_variety: "sangiovese",
    price: 26.99,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "high",
    acidNum: 5,
    tannin: "high",
    tannNum: 5,
    alcohol: "medium",
    alcoNum: 3,
    body: "medium+",
    bodyNum: 4,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 14,
    organic: true,
    biodynamic: true,
    flavor_characteristics: "",
    food_pairing: "",
    image: "",
    url: "",
    description: "",

  },
  { 
    name: "Castello di Volpaia Chianti Classico 2016",
    color: "red",
    red1_white0: 1,
    wine_region: "Italy",
    grape_variety: "sangiovese",
    price: 21.99,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "high",
    acidNum: 5,
    tannin: "high",
    tannNum: 5,
    alcohol: "medium",
    alcoNum: 3,
    body: "medium+",
    bodyNum: 4,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 14,
    organic: true,
    biodynamic: true,
    flavor_characteristics: "",
    food_pairing: "",
    image: "",
    url: "",
    description: "",

  },
  { 
    name: "Domaine Jean Chartron Bourgogne Clos de la Combe Pinot Noir 2016",
    color: "red",
    red1_white0: 1,
    wine_region: "France",
    grape_variety: "pinot noir",
    price: 23.99,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "medium",
    acidNum: 3,
    tannin: "medium",
    tannNum: 3,
    alcohol: "medium",
    alcoNum: 3,
    body: "medium",
    bodyNum: 3,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 13,
    organic: true,
    biodynamic: true,
    flavor_characteristics: "",
    food_pairing: "",
    image: "",
    url: "",
    description: "",

  },
  { 
    name: "Erath Pinot Noir",
    color: "red",
    red1_white0: 1,
    wine_region: "Oregon",
    grape_variety: "pinot noir",
    price: 16.99,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "medium",
    acidNum: 3,
    tannin: "medium",
    tannNum: 3,
    alcohol: "medium",
    alcoNum: 3,
    body: "medium",
    bodyNum: 3,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 14,
    organic: true,
    biodynamic: true,
    flavor_characteristics: "",
    food_pairing: "",
    image: "",
    url: "",
    description: "",

  },
  { 
    name: "Pardon & Fils Morgon Cote Du Py 2015",
    color: "red",
    red1_white0: 1,
    wine_region: "France",
    grape_variety: "gamay",
    price: 18.99,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "medium",
    acidNum: 3,
    tannin: "medium+",
    tannNum: 4,
    alcohol: "medium",
    alcoNum: 3,
    body: "medium",
    bodyNum: 3,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 13,
    organic: true,
    biodynamic: true,
    flavor_characteristics: "",
    food_pairing: "",
    image: "",
    url: "",
    description: "",

  },
  { 
    name: "Fratelli Alessandria Barolo Gramolere 2013",
    color: "red",
    red1_white0: 1,
    wine_region: "Italy",
    grape_variety: "nebbiolo",
    price: 65.00,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "high",
    acidNum: 5,
    tannin: "high",
    tannNum: 5,
    alcohol: "medium+",
    alcoNum: 4,
    body: "full",
    bodyNum: 5,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 15,
    organic: true,
    biodynamic: true,
    flavor_characteristics: "",
    food_pairing: "",
    image: "",
    url: "",
    description: "",

  },
  { 
    name: "Balgera Valtellina Sassella Superiore 2005",
    color: "red",
    red1_white0: 1,
    wine_region: "Italy",
    grape_variety: "nebbiolo",
    price: 32.99,
    sparkling1_still5: 0,
    sweetness: "dry",
    sweetNum: 1,
    acidity: "high",
    acidNum: 5,
    tannin: "medium+",
    tannNum: 4,
    alcohol: "medium",
    alcoNum: 3,
    body: "full",
    bodyNum: 5,
    unoaked1_oaked5: 0,
    fruity1_savory5: 0,
    alcohol_by_volume: 12,
    organic: true,
    biodynamic: true,
    flavor_characteristics: "",
    food_pairing: "",
    image: "",
    url: "",
    description: "",

  },
  
  
  
  
];

db.Wine
  .remove({})
  .then(() => db.Wine.collection.insertMany(wineSeed))
  .then(data => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
